package com.example.presentation.localization

data class AppStrings(
    val appName: String,
    val home: String,
    val categories: String,
    val search: String,
    val favorites: String,
    val settings: String,
    val admin: String,
    val featured: String,
    val recentlyAdded: String,
    val popular: String,
    val mostLiked: String,
    val mostRead: String,
    val continueReading: String,
    val newBooks: String,
    val recommended: String,
    val authors: String,
    val viewAll: String,
    val readNow: String,
    val page: String,
    val ofPages: String,
    val pages: String,
    val language: String,
    val english: String,
    val urdu: String,
    val arabic: String,
    val all: String,
    val searchPlaceholder: String,
    val recentSearches: String,
    val clear: String,
    val noResultsFound: String,
    val noResultsDesc: String,
    val bookDetails: String,
    val author: String,
    val publisher: String,
    val publicationYear: String,
    val isbn: String,
    val description: String,
    val fileSize: String,
    val rating: String,
    val likes: String,
    val comments: String,
    val addComment: String,
    val writeComment: String,
    val submit: String,
    val rateBook: String,
    val share: String,
    val bookmark: String,
    val bookmarked: String,
    val bookmarks: String,
    val noBookmarks: String,
    val favoriteAdded: String,
    val favoriteRemoved: String,
    val emptyFavorites: String,
    val emptyFavoritesDesc: String,
    val adminLogin: String,
    val enterPin: String,
    val defaultPinHint: String,
    val login: String,
    val adminDashboard: String,
    val totalBooks: String,
    val totalCategories: String,
    val totalAuthors: String,
    val addNewBook: String,
    val editBook: String,
    val deleteBook: String,
    val manageCategories: String,
    val manageAuthors: String,
    val storageManagement: String,
    val backupRestore: String,
    val title: String,
    val category: String,
    val subcategory: String,
    val selectPdf: String,
    val pdfSelected: String,
    val selectCover: String,
    val coverSelected: String,
    val saveBook: String,
    val updateBook: String,
    val bookSavedSuccess: String,
    val deleteConfirmTitle: String,
    val deleteConfirmMsg: String,
    val cancel: String,
    val delete: String,
    val edit: String,
    val jumpToPage: String,
    val jump: String,
    val readerMode: String,
    val light: String,
    val dark: String,
    val sepia: String,
    val system: String,
    val keepScreenAwake: String,
    val fitWidth: String,
    val resetZoom: String,
    val appearance: String,
    val libraryData: String,
    val exportBackup: String,
    val restoreBackup: String,
    val clearCache: String,
    val cacheCleared: String,
    val totalStorageUsed: String,
    val pdfStorage: String,
    val coversStorage: String,
    val databaseStorage: String,
    val cacheStorage: String,
    val welcomeTitle: String,
    val welcomeSubtitle: String,
    val getStarted: String,
    val selectLanguage: String,
    val englishName: String,
    val urduName: String
)

val EnglishStrings = AppStrings(
    appName = "Books Library",
    home = "Home",
    categories = "Categories",
    search = "Search",
    favorites = "Favorites",
    settings = "Settings",
    admin = "Admin",
    featured = "Featured Books",
    recentlyAdded = "Recently Added",
    popular = "Popular Books",
    mostLiked = "Most Liked",
    mostRead = "Most Read",
    continueReading = "Continue Reading",
    newBooks = "New Books",
    recommended = "Recommended Books",
    authors = "Authors",
    viewAll = "View All",
    readNow = "Read Now",
    page = "Page",
    ofPages = "of",
    pages = "Pages",
    language = "Language",
    english = "English",
    urdu = "Urdu",
    arabic = "Arabic",
    all = "All",
    searchPlaceholder = "Search books by title, author, category...",
    recentSearches = "Recent Searches",
    clear = "Clear",
    noResultsFound = "No books found",
    noResultsDesc = "Try searching with different keywords or filters.",
    bookDetails = "Book Details",
    author = "Author",
    publisher = "Publisher",
    publicationYear = "Year",
    isbn = "ISBN",
    description = "Description",
    fileSize = "File Size",
    rating = "Rating",
    likes = "Likes",
    comments = "Reviews & Comments",
    addComment = "Add Review",
    writeComment = "Write your review or comment...",
    submit = "Submit",
    rateBook = "Rate this Book",
    share = "Share",
    bookmark = "Bookmark",
    bookmarked = "Bookmarked",
    bookmarks = "Bookmarks",
    noBookmarks = "No bookmarks added for this book yet.",
    favoriteAdded = "Added to favorites",
    favoriteRemoved = "Removed from favorites",
    emptyFavorites = "No Favorites Yet",
    emptyFavoritesDesc = "Tap the heart icon on any book to add it to your favorites.",
    adminLogin = "Admin Access",
    enterPin = "Enter Admin PIN (Default: 1234)",
    defaultPinHint = "Default PIN is 1234. You can change it in settings.",
    login = "Login",
    adminDashboard = "Admin Dashboard",
    totalBooks = "Total Books",
    totalCategories = "Categories",
    totalAuthors = "Authors",
    addNewBook = "Add New Book",
    editBook = "Edit Book",
    deleteBook = "Delete Book",
    manageCategories = "Manage Categories",
    manageAuthors = "Manage Authors",
    storageManagement = "Storage Manager",
    backupRestore = "Backup & Restore",
    title = "Book Title",
    category = "Category",
    subcategory = "Subcategory",
    selectPdf = "Select PDF Document",
    pdfSelected = "PDF file selected",
    selectCover = "Select Cover Image (Optional)",
    coverSelected = "Cover image selected",
    saveBook = "Save Book to Library",
    updateBook = "Update Book",
    bookSavedSuccess = "Book saved successfully!",
    deleteConfirmTitle = "Delete Book?",
    deleteConfirmMsg = "Are you sure you want to delete this book? This will permanently delete the PDF file and reading records.",
    cancel = "Cancel",
    delete = "Delete",
    edit = "Edit",
    jumpToPage = "Jump to Page",
    jump = "Go",
    readerMode = "Reading Mode",
    light = "Light",
    dark = "Dark",
    sepia = "Sepia",
    system = "System Default",
    keepScreenAwake = "Keep Screen On While Reading",
    fitWidth = "Fit Width",
    resetZoom = "Reset Zoom",
    appearance = "Appearance & Theme",
    libraryData = "Library Storage & Data",
    exportBackup = "Export JSON Backup",
    restoreBackup = "Restore from JSON Backup",
    clearCache = "Clear Cached Render Pages",
    cacheCleared = "Cache cleared successfully!",
    totalStorageUsed = "Total Storage Used",
    pdfStorage = "PDF Books Storage",
    coversStorage = "Cover Images Storage",
    databaseStorage = "Database Storage",
    cacheStorage = "Temporary Render Cache",
    welcomeTitle = "Welcome to Books Library",
    welcomeSubtitle = "Your personal digital collection of books, literature, and knowledge with seamless offline reading.",
    getStarted = "Start Exploring",
    selectLanguage = "Select Language / زبان منتخب کریں",
    englishName = "English",
    urduName = "اردو (Urdu)"
)

val UrduStrings = AppStrings(
    appName = "کتاب گھر",
    home = "ہوم",
    categories = "شعبہ جات",
    search = "تلاش",
    favorites = "پسندیدہ",
    settings = "ترتیبات",
    admin = "منتظم (ایڈمن)",
    featured = "نمایاں کتب",
    recentlyAdded = "حال ہی میں شامل شدہ",
    popular = "مقبول کتب",
    mostLiked = "سب سے زیادہ پسندیدہ",
    mostRead = "سب سے زیادہ پڑھی جانے والی",
    continueReading = "مطالعہ جاری رکھیں",
    newBooks = "نئی کتب",
    recommended = "تجویز کردہ",
    authors = "مصنفین",
    viewAll = "تمام دیکھیں",
    readNow = "ابھی پڑھیں",
    page = "صفحہ",
    ofPages = "از",
    pages = "صفحات",
    language = "زبان",
    english = "انگریزی",
    urdu = "اردو",
    arabic = "عربی",
    all = "تمام",
    searchPlaceholder = "عنوان، مصنف یا شعبہ سے تلاش کریں...",
    recentSearches = "حالیہ تلاشیں",
    clear = "صاف کریں",
    noResultsFound = "کوئی کتاب نہیں ملی",
    noResultsDesc = "براہ کرم کوئی دوسرا لفظ تلاش کریں یا فلٹرز تبدیل کریں۔",
    bookDetails = "کتاب کی تفصیلات",
    author = "مصنف",
    publisher = "ناشر",
    publicationYear = "سال اشاعت",
    isbn = "آئی ایس بی این",
    description = "تفصیل و تعارف",
    fileSize = "فائل کا سائز",
    rating = "درجہ بندی",
    likes = "پسندیدگیاں",
    comments = "تبصرے و آراء",
    addComment = "تبصرہ شامل کریں",
    writeComment = "اپنا تبصرہ یا رائے یہاں لکھیں...",
    submit = "جمع کروائیں",
    rateBook = "کتاب کی درجہ بندی کریں",
    share = "شیئر کریں",
    bookmark = "نشان لگائیں",
    bookmarked = "نشان زدہ",
    bookmarks = "نشانیات (بک مارکس)",
    noBookmarks = "اس کتاب کے لیے ابھی کوئی بک مارک شامل نہیں کیا گیا۔",
    favoriteAdded = "پسندیدہ میں شامل کر دیا گیا",
    favoriteRemoved = "پسندیدہ سے ہٹا دیا گیا",
    emptyFavorites = "ابھی کوئی پسندیدہ کتاب نہیں ہے",
    emptyFavoritesDesc = "کسی بھی کتاب پر دل کے نشان کو دبا کر اسے اپنی پسندیدہ فہرست میں شامل کریں۔",
    adminLogin = "ایڈمن لاگ ان",
    enterPin = "ایڈمن پن درج کریں (ڈیفالٹ: 1234)",
    defaultPinHint = "ڈیفالٹ پن 1234 ہے۔ آپ ترتیبات میں اسے تبدیل کر سکتے ہیں۔",
    login = "لاگ ان کریں",
    adminDashboard = "ایڈمن ڈیش بورڈ",
    totalBooks = "کل کتب",
    totalCategories = "کل شعبہ جات",
    totalAuthors = "کل مصنفین",
    addNewBook = "نئی کتاب شامل کریں",
    editBook = "کتاب میں ترمیم کریں",
    deleteBook = "کتاب حذف کریں",
    manageCategories = "شعبہ جات کا انتظام",
    manageAuthors = "مصنفین کا انتظام",
    storageManagement = "سٹوریج کا انتظام",
    backupRestore = "بیک اپ اور بحالی",
    title = "کتاب کا نام",
    category = "شعبہ / زمرہ",
    subcategory = "ذیلی زمرہ",
    selectPdf = "پی ڈی ایف فائل منتخب کریں",
    pdfSelected = "پی ڈی ایف منتخب کر لی گئی ہے",
    selectCover = "سرورق کی تصویر منتخب کریں (اختیاری)",
    coverSelected = "سرورق منتخب ہو گیا ہے",
    saveBook = "کتاب محفوظ کریں",
    updateBook = "کتاب کی تفصیلات اپ ڈیٹ کریں",
    bookSavedSuccess = "کتاب کامیابی سے محفوظ ہو گئی!",
    deleteConfirmTitle = "کتاب حذف کریں؟",
    deleteConfirmMsg = "کیا آپ واقعی اس کتاب کو مستقل طور پر حذف کرنا چاہتے ہیں؟ پی ڈی ایف فائل اور مطالعہ کا ریکارڈ بھی مٹ جائے گا۔",
    cancel = "منسوخ",
    delete = "حذف کریں",
    edit = "ترمیم",
    jumpToPage = "صفحہ نمبر پر جائیں",
    jump = "جائیں",
    readerMode = "مطالعہ کا موڈ",
    light = "روشن (لائٹ)",
    dark = "تاریک (ڈارک)",
    sepia = "سیپیا (کاغذی)",
    system = "سسٹم ڈیفالٹ",
    keepScreenAwake = "مطالعہ کے دوران سکرین آن رکھیں",
    fitWidth = "چوڑائی کے مطابق",
    resetZoom = "زوم ری سیٹ کریں",
    appearance = "ظاہری شکل اور تھیم",
    libraryData = "سٹوریج اور ڈیٹا کا انتظام",
    exportBackup = "بیک اپ ایکسپورٹ کریں (JSON)",
    restoreBackup = "بیک اپ سے بحال کریں (JSON)",
    clearCache = "صفحات کا کیشے صاف کریں",
    cacheCleared = "کیشے کامیابی سے صاف ہو گیا!",
    totalStorageUsed = "کل استعمال شدہ سٹوریج",
    pdfStorage = "پی ڈی ایف کتب کی سٹوریج",
    coversStorage = "سرورق کی تصاویر کی سٹوریج",
    databaseStorage = "ڈیٹابیس کا سائز",
    cacheStorage = "عارضی رینڈر کیشے",
    welcomeTitle = "کتاب گھر میں خوش آمدید",
    welcomeSubtitle = "آپ کا اپنا ڈیجیٹل کتب خانہ جہاں آپ بغیر انٹرنیٹ کے بآسانی اردو اور انگریزی کتب کا مطالعہ کر سکتے ہیں۔",
    getStarted = "آغاز کریں",
    selectLanguage = "زبان منتخب کریں / Select Language",
    englishName = "English",
    urduName = "اردو (Urdu)"
)

fun getAppStrings(languageCode: String): AppStrings {
    return if (languageCode == "ur") UrduStrings else EnglishStrings
}
